### ISSUE TITLE
No support for -index-store-path argument

### ISSUE THREAD

**Issue by IMcD23** [yrnkrn/zapcc#3] opened 2018-06-18 22:19 UTC
I'm attempting to use zapcc inside of Xcode 9.2 on Mac. Xcode 9 and above pass the "-index-store-path /some/path" argument to clang, which causes errors with zapcc, since the arguments are unrecognized.

It looks like this project forked clang before [support for this argument was added](https://reviews.llvm.org/D39050).

What are your plans for keeping up to date with upstream clang?

**Comment by yrnkrn** [comment] 2018-06-20 06:12
Closing this as duplicate of #5.

**Closed by yrnkrn** 2018-06-20 06:12 UTC

**Comment by IMcD23** [comment] 2018-06-20 06:27
I built it by disabling the memcpy wrapping. This issue occurs when building a project using Xcode using zapcc, which is a separate issue from zapcc not building on macOS.

**Comment by yrnkrn** [comment] 2018-06-20 06:43
Yes, threw the memcpy thing away in c74f82da81b310dace3e1b53046d7dac12d8d676.
-index-store-path will be added if/when zapcc is re-merged with newer LLVM.
